<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>nl.maas</groupId>
        <artifactId>graal-base</artifactId>
        <version>2025.01-SNAPSHOT</version>
    </parent>

    <groupId>nl.maas.framework</groupId>
    <version>2026.01-SNAPSHOT</version>
    <artifactId>easy-frameworks</artifactId>
    <packaging>pom</packaging>

    <modules>
        <module>easy-wicket-framework-lib</module>
        <module>easy-wicket-framework-test</module>
        <module>easy-io-framework-lib</module>
        <module>easy-torrent-framework-lib</module>
<!--        <module>easy-jpa-framework</module>-->
    </modules>

    <scm>
        <connection>scm:git:ssh://git@bitbucket.org/mmaas/easy-wicket-framework.git
        </connection>
        <developerConnection>scm:git:ssh://git@bitbucket.org/mmaas/easy-wicket-framework.git
        </developerConnection>
        <url>https://mmaas@bitbucket.org/mmaas/easy-wicket-framework.git
        </url>
    </scm>

    <properties>

    </properties>

    <repositories>
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
        <repository>
            <id>objectdb</id>
            <name>ObjectDB Repository</name>
            <url>https://m2.objectdb.com</url>
        </repository>
    </repositories>

    <distributionManagement>
        <repository>
            <id>maas-fam</id>
            <name>My local repo</name>
            <url>file:///shares/repo</url>
        </repository>
    </distributionManagement>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>nl.maas.framework</groupId>
                <artifactId>easy-torrent-framework-lib</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>nl.maas.framework</groupId>
                <artifactId>easy-io-framework-lib</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>nl.maas.framework</groupId>
                <artifactId>easy-wicket-framework-lib</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.hibernate</groupId>
                <artifactId>hibernate-jpamodelgen</artifactId>
                <version>${hibernate.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-lang3</artifactId>
            </dependency>

            <dependency>
                <groupId>com.objectdb</groupId>
                <artifactId>objectdb</artifactId>
                <version>2.8.6</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.persistence</groupId>
                <artifactId>javax.persistence</artifactId>
                <version>2.1.0</version>
            </dependency>
            <dependency>
                <groupId>javax.transaction</groupId>
                <artifactId>jta</artifactId>
                <version>1.1</version>
            </dependency>
            <dependency>
                <groupId>commons-validator</groupId>
                <artifactId>commons-validator</artifactId>
                <version>1.6</version>
            </dependency>
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-lang3</artifactId>
                <version>3.12.0</version>
            </dependency>
        </dependencies>

    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
    </dependencies>

    <build>
        <pluginManagement>
            <plugins>
            </plugins>
        </pluginManagement>
        <plugins>
        </plugins>
    </build>

</project>
